import { describe, expect, it } from "vitest";

import registry from "../registry.json";
import base from "./css/base.css?raw";
import { SIDEBAR_ALIASES } from "./palette";
import { resolveTokens } from "./resolve";
import { SHADCN_TOKEN_NAMES, shadcnCssVars } from "./shadcn";

describe("shadcn variables", () => {
  it("are the resolved tokens for the default accent at standard contrast", () => {
    const vars = shadcnCssVars();
    for (const name of SHADCN_TOKEN_NAMES) {
      expect(vars.light[name]).toBe(resolveTokens("light")[name]);
      expect(vars.dark[name]).toBe(resolveTokens("dark")[name]);
    }
  });

  // A copied value would pin a consumer's sidebar to the default accent. A reference follows
  // every accent, brand and mode, as it does in theme.css.
  it("carry the sidebar aliases as references to their tokens", () => {
    for (const [name, token] of Object.entries(SIDEBAR_ALIASES)) {
      expect(shadcnCssVars().light[name]).toBe(`var(--${token})`);
      expect(shadcnCssVars().dark[name]).toBe(`var(--${token})`);
    }
  });

  it("leave the status tokens out of a consumer's stylesheet", () => {
    const names: readonly string[] = SHADCN_TOKEN_NAMES;
    expect(names.filter((name) => /^(critical|warning|success|info)/.test(name))).toEqual([]);
  });
});

// registry.json is generated by the build and committed. If this fails, the palette or base.css
// changed: run `pnpm --filter @cadence-clinical/tokens build` and commit registry.json.
describe("the committed registry theme", () => {
  const theme = registry.items.find((item) => item.name === "theme");
  if (!theme) throw new Error("registry.json has no theme item.");
  const { light, dark, theme: scale } = theme.cssVars;

  it("matches the palette", () => {
    const colors = Object.fromEntries(Object.entries(light).filter(([name]) => name !== "radius"));
    expect(colors).toEqual(shadcnCssVars().light);
    expect(dark).toEqual(shadcnCssVars().dark);
  });

  it("matches the radius and its scale in base.css", () => {
    const declared = new Map(
      [...base.matchAll(/^\s*--(radius[a-z0-9-]*):([^;]+);/gm)].map(
        ([, name = "", value = ""]): [string, string] => [name, value.trim()],
      ),
    );
    expect(declared.get("radius")).toBeDefined();
    expect(light.radius).toBe(declared.get("radius"));
    declared.delete("radius");
    expect(declared.size).toBeGreaterThan(0);
    expect(scale).toEqual(Object.fromEntries(declared));
  });
});
