import { describe, expect, it } from "vitest";

import registry from "../registry.json";
import base from "./css/base.css?raw";
import { resolveTokens } from "./resolve";
import { SHADCN_TOKEN_NAMES, shadcnCssVars } from "./shadcn";

describe("shadcn variables", () => {
  it("are the resolved tokens for the default accent at standard contrast", () => {
    const vars = shadcnCssVars();
    for (const name of SHADCN_TOKEN_NAMES) {
      expect(vars.light[name]).toBe(resolveTokens("light")[name]);
      expect(vars.dark[name]).toBe(resolveTokens("dark")[name]);
    }
  });

  it("leave the status tokens out of a consumer's stylesheet", () => {
    const names: readonly string[] = SHADCN_TOKEN_NAMES;
    expect(names.filter((name) => /^(critical|warning|success|info)/.test(name))).toEqual([]);
  });
});

// registry.json is generated by the build and committed. If this fails, the palette or base.css
// changed: run `pnpm --filter @cadence-clinical/tokens build` and commit registry.json.
describe("the committed registry theme", () => {
  const theme = registry.items.find((item) => item.name === "theme");

  it("matches the palette", () => {
    const { radius: _radius, ...light } = theme?.cssVars.light ?? {};
    expect(light).toEqual(shadcnCssVars().light);
    expect(theme?.cssVars.dark).toEqual(shadcnCssVars().dark);
  });

  it("matches the radius and its scale in base.css", () => {
    const declared = Object.fromEntries(
      [...base.matchAll(/^\s*--(radius[a-z0-9-]*):([^;]+);/gm)].map(([, name, value]) => [
        name,
        value?.trim(),
      ]),
    );
    const { radius, ...scale } = declared;
    expect(radius).toBeDefined();
    expect(theme?.cssVars.light.radius).toBe(radius);
    expect(theme?.cssVars.theme).toEqual(scale);
    expect(Object.keys(scale)).not.toEqual([]);
  });
});
