// Writes dist/theme.css from the built palette, so the CSS can never drift from the tested tokens,
// and ships typeset.css and fonts.css beside it.
import { copyFile, readFile, writeFile } from "node:fs/promises";

import { BRANDS, generateBrandCss, generateColorCss } from "../dist/index.mjs";

const base = await readFile(new URL("../src/css/base.css", import.meta.url), "utf8");
const banner = "/* Generated by @cadence-clinical/tokens. Do not edit: change src/palette.ts. */\n";

await writeFile(
  new URL("../dist/theme.css", import.meta.url),
  `${banner}\n${generateColorCss()}\n${base}`,
);

// The example brands. A page gets them only by importing brands.css, after theme.css. Each brand is
// checked as it is written, so a brand that fails contrast fails the build.
await writeFile(
  new URL("../dist/brands.css", import.meta.url),
  `${banner.replace("src/palette.ts", "src/brands.ts")}\n${Object.entries(BRANDS)
    .map(([name, brand]) => generateBrandCss(name, brand))
    .join("\n\n")}\n`,
);

for (const stylesheet of ["typeset.css", "fonts.css"]) {
  await copyFile(
    new URL(`../src/css/${stylesheet}`, import.meta.url),
    new URL(`../dist/${stylesheet}`, import.meta.url),
  );
}
