// Writes dist/theme.css from the built palette, so the CSS can never drift from the tested tokens,
// and ships typeset.css and fonts.css beside it.
import { copyFile, readFile, writeFile } from "node:fs/promises";

import { generateColorCss } from "../dist/index.mjs";

const base = await readFile(new URL("../src/css/base.css", import.meta.url), "utf8");
const banner = "/* Generated by @cadence-clinical/tokens. Do not edit: change src/palette.ts. */\n";

await writeFile(
  new URL("../dist/theme.css", import.meta.url),
  `${banner}\n${generateColorCss()}\n${base}`,
);

for (const stylesheet of ["typeset.css", "fonts.css"]) {
  await copyFile(
    new URL(`../src/css/${stylesheet}`, import.meta.url),
    new URL(`../dist/${stylesheet}`, import.meta.url),
  );
}
